[package]
name = "minio-rs"
version = "0.1.0"
authors = ["Aditya Manthramurthy <aditya.mmy@gmail.com>", "Krishnan Parthasarathi <krishnan.parthasarathi@gmail.com>"]
edition = "2018"

[dependencies]
bytes = "0.4.12"
futures = "0.1.27"
http = "0.1.17"
hyper = "0.12.28"
hyper-tls = "0.3.2"
ring = "0.14.6"
roxmltree = "0.6.0"
time = "0.1.42"
xml-rs = "0.8.0"

